### ISSUE TITLE
Crashing on 1.16.1 due to Mixin Library problem

### ISSUE THREAD

**Issue by Processhf** [modmuss50/OptiFabric#225]
[15:45:10] [main/INFO]: Loading for game Minecraft 1.16.1
[15:45:13] [main/WARN]: Warnings were found! 
 - Conflicting versions found for fabric-api-base: used 0.1.3+12a8474c7c, also found 0.1.3+12a8474c02
[15:45:13] [main/WARN]: Mod `vanilla-hammers` (${version}) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[15:45:13] [main/WARN]: Mod `extraalchemy` (1.0.3) uses 'requires' key in fabric.mod.json, which is not supported - use 'depends'
[15:45:13] [main/INFO]: [FabricLoader] Loading 96 mods: fabric-renderer-api-v1@0.2.13+eae12eb802, nomoreglowingpots@1.0.2, fabric-keybindings-v0@0.2.0+3fa9f7c502, parchment@1.0.2+1.15.2, inventorysorter@1.6.7-1.16, cardinal-components-block@2.4.0, libcd@2.4.1+1.16-pre2, step-height-entity-attribute@1.0.0, grindenchantments@1.1.0+1.16, wi_zoom@1.2-MC1.16.1, fabricloader@0.8.9+build.203, trinkets@2.6.2, vanilla-hammers@${version}, org_zeroturnaround_zt-zip@1.14, simpleteleporters@2.2.0, fabric-containers-v0@0.1.8+045df74f02, lithium@0.5.0-rc1, fabric-dimensions-v1@1.0.0+a71b305302, fabric-object-builder-api-v1@1.5.5+e00ecb5f02, staffofbuilding@1.1.0-1.16, mcf-reap@1.4.0, fabric-api-base@0.1.3+12a8474c7c, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d02, mm@2.0, cardinal-components-item@2.4.0, fabric-textures-v0@1.0.4+eae12eb802, creativebuttonmover@0.2.5, ninjaphenix-container-lib@1.1.4, fabric-rendering-fluids-v1@0.1.8+b7084faa02, cardinal-components-level@2.4.0, reach-entity-attributes@1.0.1, trees-do-not-float@1.10.87, waila@1.9.22, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8902, fabric-lifecycle-events-v1@1.0.0+b0993bc102, mo_glass@1.2-MC1.16, cardinal-components-chunk@2.4.0, cardinal-components-util@2.4.0, fabric-renderer-registries-v1@2.0.1+5a0f9a6002, betterthanmending@1.1.1, fabric-loot-tables-v1@0.1.10+059ea86602, fabric@0.14.1+build.372-1.16, org_slf4j_slf4j-api@1.7.30, bunch-o-trinkets@1.0.1, fabric-particles-v1@0.2.1+0a6f2a7002, fabric-networking-v0@0.1.10+e00ecb5f02, fabric-screen-handler-api-v1@1.0.1+f362c86e02, minecraft@1.16.1, fabric-networking-blockentity-v0@0.2.5+b50ffc7b02, modmenu@1.12.2+build.16, jankson@3.0.0+j1.2.0, cloth-basic-math@0.5.1, fabric-command-api-v1@1.0.8+5ce5339802, phosphor@0.6.0+build.7, fabric-tool-attribute-api-v1@1.1.4+5794386e02, fabric-renderer-indigo@0.3.2+4d66bed502, spinnery@3.0.40, blockus@1.6.0.1, fabric-biomes-v1@0.2.7+059ea86602, dark-loading-screen@1.3.0, fabric-events-interaction-v0@0.3.3+7066030f02, fabric-crash-report-info-v1@0.1.2+b7f9825d02, org_slf4j_slf4j-simple@1.7.30, fabric-item-api-v1@1.0.0+16acbe5b02, kyrptconfig@1.0.4-1.16, cardinal-components@2.4.0, fabric-rendering-v0@1.1.0+5341049002, fabric-key-binding-api-v1@1.0.0+e16a977402, fabric-rendering-v1@1.1.2+346247d702, cloth-config2@4.5.6, fabric-resource-loader-v0@0.2.6+f41e209802, autoconfig1u@3.2.0-unstable, chainmail@0.3.0, expandedstorage@5.3.14, fabric-content-registries-v0@0.1.9+059ea86602, universalcomponents@0.7.2+1.16-pre2, fabric-tag-extensions-v0@0.2.7+a4c57d8e02, cardinal-components-world@2.4.0, blue_endless_jankson@+, inmis@1.0.2-1.16, optifabric@1.1.0-beta1, cardinal-components-entity@2.4.0, appleskin@1.0.11, kirin@1.6.4-1.16-rc1-1.16-SNAPSHOT, fabric-commands-v0@0.2.0+52d3083602, fabric-registry-sync-v0@0.3.8+7dba2d6c02, cardinal-components-base@2.4.0, fabric-mining-levels-v0@0.1.2+b764ce9902, voxelmap@1.10.1, rebind-narrator@1.0.0, fabric-events-lifecycle-v0@0.2.0+16acbe5b02, fabric-item-groups-v0@0.2.0+438f963602, fabric-models-v0@0.1.0+dfdb52d602, extraalchemy@1.0.3, fabric-object-builders-v0@0.6.0+da175ad602, presencefootsteps@r26+1.16-rc1
[15:45:13] [main/WARN]: Mod `vanilla-hammers` (${version}) does not respect SemVer - comparison support is limited.
[15:45:13] [main/WARN]: Mod `blockus` (1.6.0.1) uses more dot-separated version components than SemVer allows; support for this is currently not guaranteed.
[15:45:13] [main/WARN]: Mod `blue_endless_jankson` (+) does not respect SemVer - comparison support is limited.
[15:45:13] [main/WARN]: Mod `presencefootsteps` (r26+1.16-rc1) does not respect SemVer - comparison support is limited.
[15:45:13] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Doug/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.8+build.18/sponge-mixin-0.8+build.18.jar Service=Knot/Fabric Env=CLIENT
[15:45:13] [main/INFO]: Loaded configuration file for Lithium (40 options available, 0 user overrides)
[15:45:13] [main/INFO]: Lithium has been successfully discovered and initialized -- your game is now faster!
[15:45:14] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-v0.mixins.json:MixinEntityTracker and should be specified in value
[15:45:15] [main/ERROR]: Critical injection failure: LVT in net/minecraft/class_761::method_22710(Lnet/minecraft/class_4587;FJZLnet/minecraft/class_4184;Lnet/minecraft/class_757;Lnet/minecraft/class_765;Lnet/minecraft/class_1159;)V has incompatible changes at opcode 1673 in callback net/minecraft/class_761::renderWandHighlight.
Expected: [Lnet/minecraft/class_3695;, Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, Lnet/minecraft/class_4597$class_4598;]
   Found: [Lnet/minecraft/class_243;, D, D, D, Lnet/minecraft/class_1159;, Z, Lnet/minecraft/class_4604;, Z, F]

**Comment by Processhf** [comment]
I've tried removing problem mods as listed in other issues such as REI and the issue still happens with any mod using mixin library.

**Comment by modmuss50** [comment]
Seems to be another mod causing the issue. Can you track down exactally what mod it is?

Updating to beta 2 should fix the REI crash.

**Comment by rosalinadev** [comment]
@modmuss50 i had the same problem of crashing, probably due to REI too, and updating to beta2 fixed it.
Other issues of the game crashing on rendering the main menu (when loading the actual menu, so the buttons and not the background) seem related.

**Comment by Processhf** [comment]
> Seems to be another mod causing the issue. Can you track down exactally what mod it is?
> 
> Updating to beta 2 should fix the REI crash.

No, I cannot. It seems like almost every single mod is causing a crash. Out of my 31 mods (including Optifabric) at least 20 of them are causing crashes on their own with optifabric. Every crash log is having a problem with Mixin being the error that actually causes the crash. Beta 2 did not fix the issue, only with REI.

**Comment by Processhf** [comment]
Looking through other users crashlogs indicate the issue is without a doubt due to Mixin incompatibility.
